---
title: Innovation Projects
timezone: America/Chicago
collections:
  atxfloods:
    title: ATXfloods
    output: true
  austin-digital-services-discovery:
    title: Austin Digital Services
    output: true
  homelessness-outreach-street-team:
    title: HOST
    output: true
  idea-accelerator:
    title: Idea Accelerator
    output: true
  permitting:
    title: Permitting
    output: true
  posts:
    title: Posts
    output: true
  resource-recovery:
    title: Resource Recovery
    output: true
  smart-city-strategic-roadmap:
    title: Smart City Strategic Roadmap
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
gems:
- jekyll-redirect-from
url: http://projects.austintexas.io
theme: jekyll-theme-zilker
permalink: pretty
github:
  repository_url: https://github.com/cityofaustin/innovation-projects
